# ==========================================================
# Role-level default permission definitions
# ADMIN handled separately — all keys granted
# ==========================================================

DEFAULT_ROLE_ACCESS = {
    "ADMIN": {},

    "MANAGEMENT": {
        "reports": True,
        "client_profile": True,
        "client_limit": True,
        "business_turnover": True,
        "top_broker": True,
        "cbr": True,
        "business_ratio": True,
        "floorsheet": True,
        "due_list": True,
        "pay_rec": True,
        "unverified_trans": True,
        "book_closure": True,
        "dpm3": True,
        "meroshare": True,
        "gallery": True,
        "live_rm": True,
        "client_comm": True,
        "bro_targets": True,
        "rm_tag": True,
        "kyc_modify": True,
        "demat_records": True,
        "transaction_monitoring": True,
        "tri_projects": True,
        "profile": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "uarf": True,
        "cache": True,
        "feedback": True,
        "cashin_out": True,
        "trade_history": True,
    },

    "MANAGER": {
        "reports": True,
        "client_profile": True,
        "client_limit": True,
        "business_turnover": True,
        "top_broker": True,
        "cbr": True,
        "business_ratio": True,
        "floorsheet": True,
        "due_list": True,
        "pay_rec": True,
        "unverified_trans": True,
        "book_closure": True,
        "dpm3": True,
        "meroshare": True,
        "gallery": True,
        "live_rm": True,
        "client_comm": True,
        "bro_targets": True,
        "rm_tag": True,
        "kyc_modify": True,
        "demat_records": True,
        "transaction_monitoring": True,
        "profile": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "uarf": True,
        "cache": True,
        "feedback": True,
        "cashin_out": True,
        "trade_history": True,
        "risk_monitoring": True,
    },

    "BM": {
        "reports": True,
        "client_profile": True,
        "client_limit": True,
        "top_broker": True,
        "cbr": True,
        "due_list": True,
        "pay_rec": True,
        "unverified_trans": True,
        "book_closure": True,
        "dpm3": True,
        "meroshare": True,
        "gallery": True,
        "live_rm": True,
        "client_comm": True,
        "rm_tag": True,
        "kyc_modify": True,
        "demat_records": True,
        "profile": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "uarf": True,
        "cache": True,
        "feedback": True,
        "cashin_out": True,
        "trade_history": True,
        "risk_monitoring": True,
    },

    "RM": {
        "bro_targets": True,
        "live_rm": True,
        "rm_tag": True,
    },

    "BRO": {
        "live_rm": True,
        "client_comm": True,
        "client_limit": True,
        "bro_targets": True,
        "rm_tag": True,
        "client_profile": True,
        "due_list": True,
        "top_broker": True,
        "book_closure": True,
        "gallery": True,
        "meroshare": True,
        "uarf": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "profile": True,
        "feedback": True,
        "trade_history": True,
        "risk_monitoring": True,
    },

    "HR": {
        "uarf": True,
        "top_broker": True,
        "pay_rec": True,
        "book_closure": True,
        "gallery": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "profile": True,
        "feedback": True,
    },

    "IT": {
        "uarf": True,
        "create_user": True,
        "top_broker": True,
        "pay_rec": True,
        "bro_targets": True,
        "book_closure": True,
        "gallery": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "profile": True,
        "feedback": True,
    },

    "VIEWER": {
        "cbr": True,
        "client_profile": True,
        "unverified_trans": True,
        "live_rm": True,
        "dpm3": True,
        "due_list": True,
        "top_broker": True,
        "rm_tag": True,
        "book_closure": True,
        "gallery": True,
        "communication_report": True,
        "project_request": True,
        "digital_vault": True,
        "profile": True,
        "feedback": True,
        "mail_cleaner": True,
    },

    "USER": {
        "book_closure": True,
        "edis_call": True,
        "demat_records": True,
        "pay_rec": True,
        "uarf": True,
        "gallery": True,
        "profile": True,
    },

    "DEFAULT": {},
}


ALL_MENU_KEYS = {
    "dashboard",
    "interest_calc",
    "pledge",
    "reports",
    "client_profile",
    "client_limit",
    "business_turnover",
    "top_broker",
    "cbr",
    "business_ratio",
    "floorsheet",
    "due_list",
    "pay_rec",
    "unverified_trans",
    "book_closure",
    "gallery",
    "dpm3",
    "edis_call",
    "live_rm",
    "client_comm",
    "bro_limit",
    "bro_targets",
    "rm_tag",
    "kyc_modify",
    "demat_records",
    "transaction_monitoring",
    "create_user",
    "active_session",
    "meroshare",
    "automation",
    "tri_projects",
    "profile",
    "communication_report",
    "project_request",
    "digital_vault",
    "uarf",
    "cache",
    "feedback",
    "view_feedback",
    "access_management",
    "cashin_out",
    "trade_history",
    "tms_code",
    "mail_cleaner",
    "risk_monitoring",
}
