base_path = f"pages/"
login_url = "streamlit_login_page.py"
dashbord_url = base_path + "_Dashboard.py" 
business_ratio_url = base_path + "BusinessRatio.py" 
book_closure_url = base_path + "BookClosure.py" 
view_feedback_url = base_path + "ViewFeedback.py" 
active_session_url = base_path + "ActiveSession.py" 
pay_rec_url = base_path + "PayableAndReceivable.py" 


cache_url = base_path + "Cache.py" 
bro_targets_and_achievements_url = base_path + "BRO Targets & Achievements.py" 
live_holdings_url = base_path + "_Live Holdings.py" 
live_rm_performance_url = base_path + "_live_rm_performance_page.py" 
dpm_3_url = base_path + "_dpm3.py" 
automation_url = base_path + "Automations.py" 
gallery_url = base_path + "Gallery.py" 



client_summary_url = base_path + "_Client Summary.py"
bro_limit_url = base_path + "_Bro Limit.py"
manager_summary_url = base_path + "_Manager Summary.py"
create_app_user_url = base_path + "_Create App User.py"
meroshare_url = base_path + "_Meroshare.py"
settings_url = base_path + "_Settings.py"
floorsheet_url = base_path + "_Floorsheet.py"
rm_tag_url = base_path + "_RM Tag.py"
due_list_url = base_path + "_Due List.py"
communication_report_url = base_path + "_CommunicationReport.py"
project_request_url = base_path + "_ProjectRequest.py"
digital_url = base_path + "DigitalVault.py"

rm_achievement_url = base_path + "_RMPerformance.py"
uarf_url = base_path + "_uarf.py"
profile_url = base_path + "_Profile.py"
feedback_url = base_path + "_Feedback.py"
logout_url = base_path + "_Logout.py"