base_path = f"pages/"
login_url = "LoginPage.py"
dashbord_url = base_path + "Dashboard.py" 
business_ratio_url = base_path + "BusinessRatio.py" 
book_closure_url = base_path + "BookClosure.py" 
view_feedback_url = base_path + "ViewFeedback.py" 
active_session_url = base_path + "ActiveSession.py" 
pay_rec_url = base_path + "PayableAndReceivable.py" 
cbr_url = base_path + "CostBenefit.py" 


cache_url = base_path + "Cache.py" 
bro_targets_and_achievements_url = base_path + "BROTargetsAndAchievements.py" 
live_holdings_url = base_path + "LiveHoldings.py" 
live_rm_performance_url = base_path + "LiveRmPerformancePage.py" 
dpm_3_url = base_path + "dpm3.py" 
automation_url = base_path + "Automations.py" 
gallery_url = base_path + "Gallery.py" 
top_broker_url = base_path + "TopBrokers.py" 



client_summary_url = base_path + "ClientSummary.py"
bro_limit_url = base_path + "BroLimit.py"
manager_summary_url = base_path + "ManagerSummary.py"
create_app_user_url = base_path + "CreateAppUser.py"
meroshare_url = base_path + "Meroshare.py"
settings_url = base_path + "Settings.py"
floorsheet_url = base_path + "Floorsheet.py"
rm_tag_url = base_path + "RMTag.py"
due_list_url = base_path + "DueList.py"
communication_report_url = base_path + "CommunicationReport.py"
project_request_url = base_path + "ProjectRequest.py"
digital_url = base_path + "DigitalVault.py"

rm_achievement_url = base_path + "RMPerformance.py"
uarf_url = base_path + "uarf.py"
profile_url = base_path + "Profile.py"
feedback_url = base_path + "Feedback.py"
logout_url = base_path + "Logout.py"