base_path = f"pages/"
login_url = "LoginPage.py"
dashbord_url = base_path + "Dashboard.py" 
business_ratio_url = base_path + "BusinessRatio.py" 
book_closure_url = base_path + "BookClosure.py" 
view_feedback_url = base_path + "ViewFeedback.py" 
active_session_url = base_path + "ActiveSession.py" 
pay_rec_url = base_path + "PayableAndReceivable.py" 
cbr_url = base_path + "CostBenefit.py" 
edis_call_url = base_path + "EDISCall.py" 
transaction_monitoring_url = base_path + "TransactionMonitoring.py"
trade_history_url = base_path + "TradeHistory.py"

unverified_trans_url = base_path + "UnverifiedTransactions.py" 
demat_records_url = base_path + "DematRecords.py" 
client_limit_url = base_path + "ClientLimit.py" 
client_remarks_url = base_path + "ClientProfile.py" 
client_communication = base_path + "ClientCommunication.py" 
kyc_modify = base_path + "KycModification.py" 
reports_url = base_path + "Reports.py" 
otp_url = base_path + "otp.py" 
cashin_out_url = base_path + "CashInOut.py" 

access_management_url = base_path + "AccessManagement.py"

cache_url = base_path + "Cache.py" 
interest_calc_url = base_path + "InterestCalculation.py" 
bro_targets_and_achievements_url = base_path + "BROTargetsAndAchievements.py" 
live_holdings_url = base_path + "LiveHoldings.py" 
live_rm_performance_url = base_path + "LiveRmPerformance.py" 
dpm_3_url = base_path + "dpm3.py" 
automation_url = base_path + "Automations.py" 
gallery_url = base_path + "Gallery.py" 
top_broker_url = base_path + "TopBrokers.py" 
business_turnover_url = base_path + "BusinessTurnover.py" 



client_summary_url = base_path + "ClientSummary.py"
bro_limit_url = base_path + "BroLimit.py"
manager_summary_url = base_path + "ManagerSummary.py"
create_app_user_url = base_path + "CreateAppUser.py"
meroshare_url = base_path + "Meroshare.py"
settings_url = base_path + "Settings.py"
floorsheet_url = base_path + "Floorsheet.py"
rm_tag_url = base_path + "RMTag.py"
due_list_url = base_path + "DueList.py"
communication_report_url = base_path + "CommunicationReport.py"
project_request_url = base_path + "ProjectRequest.py"
digital_url = base_path + "DigitalVault.py"

rm_achievement_url = base_path + "RMPerformance.py"
uarf_url = base_path + "uarf.py"
profile_url = base_path + "Profile.py"
tri_projects_url = base_path + "TriProjects.py"
feedback_url = base_path + "Feedback.py"
logout_url = base_path + "Logout.py"

tms_code_url = base_path + "TmsCode.py"