[client]
showSidebarNavigation = false
showErrorDetails = false
#toolbarMode = "minimal"



[server]
maxUploadSize = 1024  # in MB



[logger]
level="error"




#[browser]
#gatherUsageStats = false

#[ui]
#hideTopBar = true